name: "Versioning"

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: versioning
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.new_version }}
          release_name: Release ${{ steps.versioning.outputs.new_version }}
          body: ''
          draft: false
          prerelease: ${{ contains(steps.versioning.outputs.new_version, '-') }}
