name: "Versioning"

on:
  push:
    branches:
      - master

jobs:
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        uses: ./actions/semver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}